# Generated by Django 4.2.5 on 2024-02-27 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NewsPortal', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='authorUser',
            new_name='AuthorUser',
        ),
    ]
